#include "initialize_oae_animation_bank.h"

OAEAnimationBank initializeOAEAnimationBank(const TextureBank& textureBankToUse)
{
	OAEAnimationBank returnValue;

	OAEAnimation aliceWalkDownAnimation = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationHoe = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationWateringCan = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationWateringCanEmpty = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationTomatoSeeds = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationCucumberSeeds = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationCarrotSeeds = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationTomatoCrate = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationTomatoCrateFilled = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationCucumberCrate = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationCucumberCrateFilled = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationCarrotCrate = OAEAnimation();
	OAEAnimation aliceWalkDownAnimationCarrotCrateFilled = OAEAnimation();

	OAEAnimation aliceWalkUpAnimation = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationHoe = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationWateringCan = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationWateringCanEmpty = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationTomatoSeeds = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationCucumberSeeds = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationCarrotSeeds = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationTomatoCrate = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationTomatoCrateFilled = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationCucumberCrate = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationCucumberCrateFilled = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationCarrotCrate = OAEAnimation();
	OAEAnimation aliceWalkUpAnimationCarrotCrateFilled = OAEAnimation();

	OAEAnimation aliceWalkLeftAnimation = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationHoe = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationWateringCan = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationWateringCanEmpty = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationTomatoSeeds = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationCucumberSeeds = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationCarrotSeeds = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationTomatoCrate = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationTomatoCrateFilled = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationCucumberCrate = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationCucumberCrateFilled = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationCarrotCrate = OAEAnimation();
	OAEAnimation aliceWalkLeftAnimationCarrotCrateFilled = OAEAnimation();

	OAEAnimation aliceWalkRightAnimation = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationHoe = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationWateringCan = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationWateringCanEmpty = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationTomatoSeeds = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationCucumberSeeds = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationCarrotSeeds = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationTomatoCrate = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationTomatoCrateFilled = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationCucumberCrate = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationCucumberCrateFilled = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationCarrotCrate = OAEAnimation();
	OAEAnimation aliceWalkRightAnimationCarrotCrateFilled = OAEAnimation();

	OAEAnimation saveWarningAnimation = OAEAnimation();

	aliceWalkDownAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_HOE),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_HOE),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_WATERING_CAN),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_WATERING_CAN),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkDownAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_HOE),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_HOE),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_WATERING_CAN),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_WATERING_CAN),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkUpAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkUpAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_HOE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_HOE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_HOE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_HOE),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_WATERING_CAN),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_WATERING_CAN),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_WATERING_CAN),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_WATERING_CAN),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_WATERING_CAN),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkLeftAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkLeftAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_HOE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_HOE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_HOE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_HOE),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_WATERING_CAN),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_WATERING_CAN),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_WATERING_CAN),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_WATERING_CAN),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_WATERING_CAN_EMPTY),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_WATERING_CAN),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_TOMATO_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CUCUMBER_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CARROT_SEEDS),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_TOMATO_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_TOMATO_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CUCUMBER_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CUCUMBER_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CARROT_CRATE),DEFAULT_ANIMATION_SPEED);

	aliceWalkRightAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);
	aliceWalkRightAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CARROT_CRATE_FILLED),DEFAULT_ANIMATION_SPEED);

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK, aliceWalkDownAnimation);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_HOE, aliceWalkDownAnimationHoe);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_WATERING_CAN, aliceWalkDownAnimationWateringCan);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_WATERING_CAN_EMPTY, aliceWalkDownAnimationWateringCanEmpty);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_TOMATO_SEEDS, aliceWalkDownAnimationTomatoSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CUCUMBER_SEEDS, aliceWalkDownAnimationCucumberSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CARROT_SEEDS, aliceWalkDownAnimationCarrotSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_TOMATO_CRATE, aliceWalkDownAnimationTomatoCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_TOMATO_CRATE_FILLED, aliceWalkDownAnimationTomatoCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CUCUMBER_CRATE, aliceWalkDownAnimationCucumberCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CUCUMBER_CRATE_FILLED, aliceWalkDownAnimationCucumberCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CARROT_CRATE, aliceWalkDownAnimationCarrotCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CARROT_CRATE_FILLED, aliceWalkDownAnimationCarrotCrateFilled);

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK, aliceWalkUpAnimation);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_HOE, aliceWalkUpAnimationHoe);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_WATERING_CAN, aliceWalkUpAnimationWateringCan);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_WATERING_CAN_EMPTY, aliceWalkUpAnimationWateringCanEmpty);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_TOMATO_SEEDS, aliceWalkUpAnimationTomatoSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CUCUMBER_SEEDS, aliceWalkUpAnimationCucumberSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CARROT_SEEDS, aliceWalkUpAnimationCarrotSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_TOMATO_CRATE, aliceWalkUpAnimationTomatoCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_TOMATO_CRATE_FILLED, aliceWalkUpAnimationTomatoCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CUCUMBER_CRATE, aliceWalkUpAnimationCucumberCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CUCUMBER_CRATE_FILLED, aliceWalkUpAnimationCucumberCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CARROT_CRATE, aliceWalkUpAnimationCarrotCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CARROT_CRATE_FILLED, aliceWalkUpAnimationCarrotCrateFilled);

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK, aliceWalkLeftAnimation);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_HOE, aliceWalkLeftAnimationHoe);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_WATERING_CAN, aliceWalkLeftAnimationWateringCan);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_WATERING_CAN_EMPTY, aliceWalkLeftAnimationWateringCanEmpty);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_TOMATO_SEEDS, aliceWalkLeftAnimationTomatoSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CUCUMBER_SEEDS, aliceWalkLeftAnimationCucumberSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CARROT_SEEDS, aliceWalkLeftAnimationCarrotSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_TOMATO_CRATE, aliceWalkLeftAnimationTomatoCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_TOMATO_CRATE_FILLED, aliceWalkLeftAnimationTomatoCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CUCUMBER_CRATE, aliceWalkLeftAnimationCucumberCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CUCUMBER_CRATE_FILLED, aliceWalkLeftAnimationCucumberCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CARROT_CRATE, aliceWalkLeftAnimationCarrotCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CARROT_CRATE_FILLED, aliceWalkLeftAnimationCarrotCrateFilled);

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK, aliceWalkRightAnimation);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_HOE, aliceWalkRightAnimationHoe);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_WATERING_CAN, aliceWalkRightAnimationWateringCan);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_WATERING_CAN_EMPTY, aliceWalkRightAnimationWateringCanEmpty);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_TOMATO_SEEDS, aliceWalkRightAnimationTomatoSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CUCUMBER_SEEDS, aliceWalkRightAnimationCucumberSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CARROT_SEEDS, aliceWalkRightAnimationCarrotSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_TOMATO_CRATE, aliceWalkRightAnimationTomatoCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_TOMATO_CRATE_FILLED, aliceWalkRightAnimationTomatoCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CUCUMBER_CRATE, aliceWalkRightAnimationCucumberCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CUCUMBER_CRATE_FILLED, aliceWalkRightAnimationCucumberCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CARROT_CRATE, aliceWalkRightAnimationCarrotCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CARROT_CRATE_FILLED, aliceWalkRightAnimationCarrotCrateFilled);

	saveWarningAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_SAVE_WARNING_FRAME_ONE),DEFAULT_ANIMATION_SPEED);
	saveWarningAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_SAVE_WARNING_FRAME_TWO),DEFAULT_ANIMATION_SPEED);
	saveWarningAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_SAVE_WARNING_FRAME_THREE),DEFAULT_ANIMATION_SPEED);
	saveWarningAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_SAVE_WARNING_FRAME_FOUR),DEFAULT_ANIMATION_SPEED);

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_SAVE_WARNING, saveWarningAnimation);
	
	return returnValue;
}
