#include "initialize_oae_animation_bank.h"

OAEAnimationBank initializeOAEAnimationBank(const TextureBank& textureBankToUse)
{
	OAEAnimationBank returnValue;

	OAEAnimation aliceWalkDownAnimation = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationHoe = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationWateringCan = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationWateringCanEmpty = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationTomatoSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationCucumberSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationCarrotSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationTomatoCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationTomatoCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationCucumberCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationCucumberCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationCarrotCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkDownAnimationCarrotCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);

	OAEAnimation aliceWalkUpAnimation = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationHoe = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationWateringCan = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationWateringCanEmpty = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationTomatoSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationCucumberSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationCarrotSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationTomatoCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationTomatoCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationCucumberCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationCucumberCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationCarrotCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkUpAnimationCarrotCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);

	OAEAnimation aliceWalkLeftAnimation = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationHoe = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationWateringCan = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationWateringCanEmpty = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationTomatoSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationCucumberSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationCarrotSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationTomatoCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationTomatoCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationCucumberCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationCucumberCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationCarrotCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkLeftAnimationCarrotCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);

	OAEAnimation aliceWalkRightAnimation = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationHoe = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationWateringCan = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationWateringCanEmpty = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationTomatoSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationCucumberSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationCarrotSeeds = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationTomatoCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationTomatoCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationCucumberCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationCucumberCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationCarrotCrate = OAEAnimation(DEFAULT_ANIMATION_SPEED);
	OAEAnimation aliceWalkRightAnimationCarrotCrateFilled = OAEAnimation(DEFAULT_ANIMATION_SPEED);

	aliceWalkDownAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE));
	aliceWalkDownAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO));

	aliceWalkDownAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_HOE));
	aliceWalkDownAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_HOE));

	aliceWalkDownAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_WATERING_CAN));
	aliceWalkDownAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_WATERING_CAN));

	aliceWalkDownAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_WATERING_CAN_EMPTY));
	aliceWalkDownAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_WATERING_CAN_EMPTY));

	aliceWalkDownAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_TOMATO_SEEDS));
	aliceWalkDownAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_TOMATO_SEEDS));

	aliceWalkDownAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CUCUMBER_SEEDS));
	aliceWalkDownAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CUCUMBER_SEEDS));

	aliceWalkDownAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CARROT_SEEDS));
	aliceWalkDownAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CARROT_SEEDS));

	aliceWalkDownAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_TOMATO_CRATE));
	aliceWalkDownAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_TOMATO_CRATE));

	aliceWalkDownAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_TOMATO_CRATE_FILLED));
	aliceWalkDownAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_TOMATO_CRATE_FILLED));

	aliceWalkDownAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CUCUMBER_CRATE));
	aliceWalkDownAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CUCUMBER_CRATE));

	aliceWalkDownAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CUCUMBER_CRATE_FILLED));
	aliceWalkDownAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CUCUMBER_CRATE_FILLED));

	aliceWalkDownAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CARROT_CRATE));
	aliceWalkDownAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CARROT_CRATE));

	aliceWalkDownAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE_CARROT_CRATE_FILLED));
	aliceWalkDownAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO_CARROT_CRATE_FILLED));

	aliceWalkUpAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE));
	aliceWalkUpAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO));

	aliceWalkUpAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_HOE));
	aliceWalkUpAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_HOE));

	aliceWalkUpAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_WATERING_CAN));
	aliceWalkUpAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_WATERING_CAN));

	aliceWalkUpAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_WATERING_CAN_EMPTY));
	aliceWalkUpAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_WATERING_CAN_EMPTY));

	aliceWalkUpAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_TOMATO_SEEDS));
	aliceWalkUpAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_TOMATO_SEEDS));

	aliceWalkUpAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CUCUMBER_SEEDS));
	aliceWalkUpAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CUCUMBER_SEEDS));

	aliceWalkUpAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CARROT_SEEDS));
	aliceWalkUpAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CARROT_SEEDS));

	aliceWalkUpAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_TOMATO_CRATE));
	aliceWalkUpAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_TOMATO_CRATE));

	aliceWalkUpAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_TOMATO_CRATE_FILLED));
	aliceWalkUpAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_TOMATO_CRATE_FILLED));

	aliceWalkUpAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CUCUMBER_CRATE));
	aliceWalkUpAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CUCUMBER_CRATE));

	aliceWalkUpAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CUCUMBER_CRATE_FILLED));
	aliceWalkUpAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CUCUMBER_CRATE_FILLED));

	aliceWalkUpAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CARROT_CRATE));
	aliceWalkUpAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CARROT_CRATE));

	aliceWalkUpAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE_CARROT_CRATE_FILLED));
	aliceWalkUpAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO_CARROT_CRATE_FILLED));

	aliceWalkLeftAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE));
	aliceWalkLeftAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE));
	aliceWalkLeftAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE));
	aliceWalkLeftAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO));

	aliceWalkLeftAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_HOE));
	aliceWalkLeftAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_HOE));
	aliceWalkLeftAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_HOE));
	aliceWalkLeftAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_HOE));

	aliceWalkLeftAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_WATERING_CAN));
	aliceWalkLeftAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_WATERING_CAN));
	aliceWalkLeftAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_WATERING_CAN));
	aliceWalkLeftAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_WATERING_CAN));

	aliceWalkLeftAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_WATERING_CAN_EMPTY));
	aliceWalkLeftAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_WATERING_CAN_EMPTY));
	aliceWalkLeftAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_WATERING_CAN_EMPTY));
	aliceWalkLeftAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_WATERING_CAN));

	aliceWalkLeftAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_SEEDS));
	aliceWalkLeftAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_TOMATO_SEEDS));
	aliceWalkLeftAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_SEEDS));
	aliceWalkLeftAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_TOMATO_SEEDS));

	aliceWalkLeftAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_SEEDS));
	aliceWalkLeftAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CUCUMBER_SEEDS));
	aliceWalkLeftAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_SEEDS));
	aliceWalkLeftAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CUCUMBER_SEEDS));

	aliceWalkLeftAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_SEEDS));
	aliceWalkLeftAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CARROT_SEEDS));
	aliceWalkLeftAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_SEEDS));
	aliceWalkLeftAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CARROT_SEEDS));

	aliceWalkLeftAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_CRATE));
	aliceWalkLeftAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_TOMATO_CRATE));
	aliceWalkLeftAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_CRATE));
	aliceWalkLeftAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_TOMATO_CRATE));

	aliceWalkLeftAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_CRATE_FILLED));
	aliceWalkLeftAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_TOMATO_CRATE_FILLED));
	aliceWalkLeftAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_TOMATO_CRATE_FILLED));
	aliceWalkLeftAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_TOMATO_CRATE_FILLED));

	aliceWalkLeftAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_CRATE));
	aliceWalkLeftAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CUCUMBER_CRATE));
	aliceWalkLeftAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_CRATE));
	aliceWalkLeftAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CUCUMBER_CRATE));

	aliceWalkLeftAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_CRATE_FILLED));
	aliceWalkLeftAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CUCUMBER_CRATE_FILLED));
	aliceWalkLeftAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CUCUMBER_CRATE_FILLED));
	aliceWalkLeftAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CUCUMBER_CRATE_FILLED));

	aliceWalkLeftAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_CRATE));
	aliceWalkLeftAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CARROT_CRATE));
	aliceWalkLeftAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_CRATE));
	aliceWalkLeftAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CARROT_CRATE));

	aliceWalkLeftAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_CRATE_FILLED));
	aliceWalkLeftAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE_CARROT_CRATE_FILLED));
	aliceWalkLeftAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE_CARROT_CRATE_FILLED));
	aliceWalkLeftAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO_CARROT_CRATE_FILLED));

	aliceWalkRightAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE));
	aliceWalkRightAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE));
	aliceWalkRightAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE));
	aliceWalkRightAnimation.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO));

	aliceWalkRightAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_HOE));
	aliceWalkRightAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_HOE));
	aliceWalkRightAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_HOE));
	aliceWalkRightAnimationHoe.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_HOE));

	aliceWalkRightAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_WATERING_CAN));
	aliceWalkRightAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_WATERING_CAN));
	aliceWalkRightAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_WATERING_CAN));
	aliceWalkRightAnimationWateringCan.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_WATERING_CAN));

	aliceWalkRightAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_WATERING_CAN_EMPTY));
	aliceWalkRightAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_WATERING_CAN_EMPTY));
	aliceWalkRightAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_WATERING_CAN_EMPTY));
	aliceWalkRightAnimationWateringCanEmpty.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_WATERING_CAN));

	aliceWalkRightAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_SEEDS));
	aliceWalkRightAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_TOMATO_SEEDS));
	aliceWalkRightAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_SEEDS));
	aliceWalkRightAnimationTomatoSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_TOMATO_SEEDS));

	aliceWalkRightAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_SEEDS));
	aliceWalkRightAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CUCUMBER_SEEDS));
	aliceWalkRightAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_SEEDS));
	aliceWalkRightAnimationCucumberSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CUCUMBER_SEEDS));

	aliceWalkRightAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_SEEDS));
	aliceWalkRightAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CARROT_SEEDS));
	aliceWalkRightAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_SEEDS));
	aliceWalkRightAnimationCarrotSeeds.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CARROT_SEEDS));

	aliceWalkRightAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_CRATE));
	aliceWalkRightAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_TOMATO_CRATE));
	aliceWalkRightAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_CRATE));
	aliceWalkRightAnimationTomatoCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_TOMATO_CRATE));

	aliceWalkRightAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_CRATE_FILLED));
	aliceWalkRightAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_TOMATO_CRATE_FILLED));
	aliceWalkRightAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_TOMATO_CRATE_FILLED));
	aliceWalkRightAnimationTomatoCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_TOMATO_CRATE_FILLED));

	aliceWalkRightAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_CRATE));
	aliceWalkRightAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CUCUMBER_CRATE));
	aliceWalkRightAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_CRATE));
	aliceWalkRightAnimationCucumberCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CUCUMBER_CRATE));

	aliceWalkRightAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_CRATE_FILLED));
	aliceWalkRightAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CUCUMBER_CRATE_FILLED));
	aliceWalkRightAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CUCUMBER_CRATE_FILLED));
	aliceWalkRightAnimationCucumberCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CUCUMBER_CRATE_FILLED));

	aliceWalkRightAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_CRATE));
	aliceWalkRightAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CARROT_CRATE));
	aliceWalkRightAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_CRATE));
	aliceWalkRightAnimationCarrotCrate.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CARROT_CRATE));

	aliceWalkRightAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_CRATE_FILLED));
	aliceWalkRightAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE_CARROT_CRATE_FILLED));
	aliceWalkRightAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE_CARROT_CRATE_FILLED));
	aliceWalkRightAnimationCarrotCrateFilled.appendTextureToAnimation(textureBankToUse.getTextureAssociatedWithReferenceNumber(TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO_CARROT_CRATE_FILLED));

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK, aliceWalkDownAnimation);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_HOE, aliceWalkDownAnimationHoe);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_WATERING_CAN, aliceWalkDownAnimationWateringCan);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_WATERING_CAN_EMPTY, aliceWalkDownAnimationWateringCanEmpty);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_TOMATO_SEEDS, aliceWalkDownAnimationTomatoSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CUCUMBER_SEEDS, aliceWalkDownAnimationCucumberSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CARROT_SEEDS, aliceWalkDownAnimationCarrotSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_TOMATO_CRATE, aliceWalkDownAnimationTomatoCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_TOMATO_CRATE_FILLED, aliceWalkDownAnimationTomatoCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CUCUMBER_CRATE, aliceWalkDownAnimationCucumberCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CUCUMBER_CRATE_FILLED, aliceWalkDownAnimationCucumberCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CARROT_CRATE, aliceWalkDownAnimationCarrotCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK_CARROT_CRATE_FILLED, aliceWalkDownAnimationCarrotCrateFilled);

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK, aliceWalkUpAnimation);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_HOE, aliceWalkUpAnimationHoe);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_WATERING_CAN, aliceWalkUpAnimationWateringCan);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_WATERING_CAN_EMPTY, aliceWalkUpAnimationWateringCanEmpty);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_TOMATO_SEEDS, aliceWalkUpAnimationTomatoSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CUCUMBER_SEEDS, aliceWalkUpAnimationCucumberSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CARROT_SEEDS, aliceWalkUpAnimationCarrotSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_TOMATO_CRATE, aliceWalkUpAnimationTomatoCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_TOMATO_CRATE_FILLED, aliceWalkUpAnimationTomatoCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CUCUMBER_CRATE, aliceWalkUpAnimationCucumberCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CUCUMBER_CRATE_FILLED, aliceWalkUpAnimationCucumberCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CARROT_CRATE, aliceWalkUpAnimationCarrotCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK_CARROT_CRATE_FILLED, aliceWalkUpAnimationCarrotCrateFilled);

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK, aliceWalkLeftAnimation);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_HOE, aliceWalkLeftAnimationHoe);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_WATERING_CAN, aliceWalkLeftAnimationWateringCan);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_WATERING_CAN_EMPTY, aliceWalkLeftAnimationWateringCanEmpty);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_TOMATO_SEEDS, aliceWalkLeftAnimationTomatoSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CUCUMBER_SEEDS, aliceWalkLeftAnimationCucumberSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CARROT_SEEDS, aliceWalkLeftAnimationCarrotSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_TOMATO_CRATE, aliceWalkLeftAnimationTomatoCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_TOMATO_CRATE_FILLED, aliceWalkLeftAnimationTomatoCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CUCUMBER_CRATE, aliceWalkLeftAnimationCucumberCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CUCUMBER_CRATE_FILLED, aliceWalkLeftAnimationCucumberCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CARROT_CRATE, aliceWalkLeftAnimationCarrotCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK_CARROT_CRATE_FILLED, aliceWalkLeftAnimationCarrotCrateFilled);

	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK, aliceWalkRightAnimation);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_HOE, aliceWalkRightAnimationHoe);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_WATERING_CAN, aliceWalkRightAnimationWateringCan);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_WATERING_CAN_EMPTY, aliceWalkRightAnimationWateringCanEmpty);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_TOMATO_SEEDS, aliceWalkRightAnimationTomatoSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CUCUMBER_SEEDS, aliceWalkRightAnimationCucumberSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CARROT_SEEDS, aliceWalkRightAnimationCarrotSeeds);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_TOMATO_CRATE, aliceWalkRightAnimationTomatoCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_TOMATO_CRATE_FILLED, aliceWalkRightAnimationTomatoCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CUCUMBER_CRATE, aliceWalkRightAnimationCucumberCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CUCUMBER_CRATE_FILLED, aliceWalkRightAnimationCucumberCrateFilled);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CARROT_CRATE, aliceWalkRightAnimationCarrotCrate);
	returnValue.saveOAEAnimationWithReferenceNumber(ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CARROT_CRATE_FILLED, aliceWalkRightAnimationCarrotCrateFilled);
	
	return returnValue;
}
