#ifndef REFERENCE_NUMBER_ENUMS_H
#define REFERENCE_NUMBER_ENUMS_H

enum worldObjectReferenceNumbers
{
    WORLD_OBJECT_REF_NUMBER_INVALID = 0,
    WORLD_OBJECT_REF_NUMBER_HOE = 1,
    WORLD_OBJECT_REF_NUMBER_HOUSE = 2,
    WORLD_OBJECT_REF_NUMBER_WELL = 3,
    WORLD_OBJECT_REF_NUMBER_WATERING_CAN = 4,
	WORLD_OBJECT_REF_NUMBER_TOP_BORDER_COLLISION_BOX = 5,
	WORLD_OBJECT_REF_NUMBER_BOTTOM_BORDER_COLLISION_BOX = 6,
	WORLD_OBJECT_REF_NUMBER_LEFT_BORDER_COLLISION_BOX = 7,
	WORLD_OBJECT_REF_NUMBER_RIGHT_BORDER_COLLISION_BOX = 8,

	WORLD_OBJECT_REF_NUMBER_TOMATO_SEED_PACKET_ONE = 9,
	WORLD_OBJECT_REF_NUMBER_CUCUMBER_SEED_PACKET_ONE = 10,
	WORLD_OBJECT_REF_NUMBER_CARROT_SEED_PACKET_ONE = 11,
	WORLD_OBJECT_REF_NUMBER_TOMATO_SEED_PACKET_TWO = 12,
	WORLD_OBJECT_REF_NUMBER_CUCUMBER_SEED_PACKET_TWO = 13,
	WORLD_OBJECT_REF_NUMBER_CARROT_SEED_PACKET_TWO = 14,
	WORLD_OBJECT_REF_NUMBER_TOMATO_SEED_PACKET_THREE = 15,
	WORLD_OBJECT_REF_NUMBER_CUCUMBER_SEED_PACKET_THREE = 16,
	WORLD_OBJECT_REF_NUMBER_CARROT_SEED_PACKET_THREE = 17,
	
	WORLD_OBJECT_REF_NUMBER_TOMATO_CRATE_ONE = 18,
	WORLD_OBJECT_REF_NUMBER_CUCUMBER_CRATE_ONE = 19,
	WORLD_OBJECT_REF_NUMBER_CARROT_CRATE_ONE = 20,
	WORLD_OBJECT_REF_NUMBER_TOMATO_CRATE_TWO = 21,
	WORLD_OBJECT_REF_NUMBER_CUCUMBER_CRATE_TWO = 22,
	WORLD_OBJECT_REF_NUMBER_CARROT_CRATE_TWO = 23,
	WORLD_OBJECT_REF_NUMBER_TOMATO_CRATE_THREE = 24,
	WORLD_OBJECT_REF_NUMBER_CUCUMBER_CRATE_THREE = 25,
	WORLD_OBJECT_REF_NUMBER_CARROT_CRATE_THREE = 26
};

enum textureBankReferenceNumbers
{
	TEXTURE_BANK_REF_NUMBER_INVISIBLE = 0,
    TEXTURE_BANK_REF_NUMBER_OUT_OF_BOUNDS_GRASS = 1,
    TEXTURE_BANK_REF_NUMBER_IN_BOUNDS_GRASS = 2,
    TEXTURE_BANK_REF_NUMBER_UNWATERED_TILLED_DIRT = 3,
    TEXTURE_BANK_REF_NUMBER_WATERED_TILLED_DIRT = 4,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_BASE = 5,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE = 6,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO = 7,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_BASE = 8,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE = 9,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO = 10,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE = 11,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE = 12,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO = 13,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE = 14,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE = 15,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO = 16,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_HOE = 17,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_HOUSE = 18,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_WELL = 19,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_WATERING_CAN = 20,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_BACKGROUND = 21,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_SELECT_GAME_BUTTON = 22,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_CREDITS_BUTTON = 23,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_EXIT_BUTTON = 24,
	TEXTURE_BANK_REF_NUMBER_WINDOW_X = 25,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_SAVE_GAME_ONE_BACKGROUND_TEXTURE = 26,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_SAVE_GAME_TWO_BACKGROUND_TEXTURE = 27,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_SAVE_GAME_THREE_BACKGROUND_TEXTURE = 28,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_DELETE_SAVE_GAME_ICON_TEXTURE = 29
};

enum animationBankReferenceNumbers
{
    ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK = 0,
    ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK = 1,
    ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK = 2,
    ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK = 3
};

#endif
