#ifndef REFERENCE_NUMBER_ENUMS_H
#define REFERENCE_NUMBER_ENUMS_H

enum worldObjectReferenceNumbers
{
    WORLD_OBJECT_REF_NUMBER_INVALID = 0,
    WORLD_OBJECT_REF_NUMBER_HOE = 1,
    WORLD_OBJECT_REF_NUMBER_HOUSE = 2,
    WORLD_OBJECT_REF_NUMBER_WELL = 3,
    WORLD_OBJECT_REF_NUMBER_WATERING_CAN = 4
};

enum textureBankReferenceNumbers
{
    TEXTURE_BANK_REF_NUMBER_OUT_OF_BOUNDS_GRASS = 0,
    TEXTURE_BANK_REF_NUMBER_IN_BOUNDS_GRASS = 1,
    TEXTURE_BANK_REF_NUMBER_UNWATERED_TILLED_DIRT = 2,
    TEXTURE_BANK_REF_NUMBER_WATERED_TILLED_DIRT = 3,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_BASE = 4,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE = 5,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO = 6,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_BASE = 7,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE = 8,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO = 9,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE = 8,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE = 10,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO = 11,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE = 12,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE = 13,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO = 14,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_HOE = 15,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_HOUSE = 16,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_WELL = 17,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_WATERING_CAN = 18
};

enum animationBankReferenceNumbers
{
    ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK = 0,
    ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK = 1,
    ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK = 2,
    ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK = 3
};

#endif
