#ifndef REFERENCE_NUMBER_ENUMS_H
#define REFERENCE_NUMBER_ENUMS_H

enum worldObjectReferenceNumbers
{
    WORLD_OBJECT_REF_NUMBER_INVALID = 0,
    WORLD_OBJECT_REF_NUMBER_HOE = 1,
    WORLD_OBJECT_REF_NUMBER_HOUSE = 2,
    WORLD_OBJECT_REF_NUMBER_WELL = 3,
    WORLD_OBJECT_REF_NUMBER_WATERING_CAN = 4,
	WORLD_OBJECT_REF_NUMBER_TOP_BORDER_COLLISION_BOX = 5,
	WORLD_OBJECT_REF_NUMBER_BOTTOM_BORDER_COLLISION_BOX = 6,
	WORLD_OBJECT_REF_NUMBER_LEFT_BORDER_COLLISION_BOX = 7,
	WORLD_OBJECT_REF_NUMBER_RIGHT_BORDER_COLLISION_BOX = 8
};

enum textureBankReferenceNumbers
{
	TEXTURE_BANK_REF_NUMBER_INVISIBLE = 0,
    TEXTURE_BANK_REF_NUMBER_OUT_OF_BOUNDS_GRASS = 1,
    TEXTURE_BANK_REF_NUMBER_IN_BOUNDS_GRASS = 2,
    TEXTURE_BANK_REF_NUMBER_UNWATERED_TILLED_DIRT = 3,
    TEXTURE_BANK_REF_NUMBER_WATERED_TILLED_DIRT = 4,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_BASE = 5,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_ONE = 6,
    TEXTURE_BANK_REF_NUMBER_ALICE_DOWN_WALK_CYCLE_TWO = 7,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_BASE = 8,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_ONE = 9,
    TEXTURE_BANK_REF_NUMBER_ALICE_UP_WALK_CYCLE_TWO = 10,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_BASE = 11,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_ONE = 12,
    TEXTURE_BANK_REF_NUMBER_ALICE_LEFT_WALK_CYCLE_TWO = 13,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_BASE = 14,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_ONE = 15,
    TEXTURE_BANK_REF_NUMBER_ALICE_RIGHT_WALK_CYCLE_TWO = 16,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_HOE = 17,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_HOUSE = 18,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_WELL = 19,
    TEXTURE_BANK_REF_NUMBER_WORLD_OBJECT_WATERING_CAN = 20,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_BACKGROUND = 21,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_SELECT_GAME_BUTTON = 22,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_CREDITS_BUTTON = 23,
	TEXTURE_BANK_REF_NUMBER_MAIN_MENU_SCREEN_EXIT_BUTTON = 24,
	TEXTURE_BANK_REF_NUMBER_WINDOW_X = 25
};

enum animationBankReferenceNumbers
{
    ANIMATION_BANK_REF_NUMBER_ALICE_DOWN_WALK = 0,
    ANIMATION_BANK_REF_NUMBER_ALICE_UP_WALK = 1,
    ANIMATION_BANK_REF_NUMBER_ALICE_LEFT_WALK = 2,
    ANIMATION_BANK_REF_NUMBER_ALICE_RIGHT_WALK = 3
};

#endif
