#ifndef WORLD_OBJECT_PROPERTIES
#define WORLD_OBJECT_PROPERTIES

enum WorldObjectProperty
{
	WORLD_OBJECT_PROPERTY_PICKUPABLE = 0,
	WORLD_OBJECT_PROPERTY_ACTION_FILL_WATER_CONTAINER = 1,
	WORLD_OBJECT_PROPERTY_ACTION_SLEEP = 2,
	WORLD_OBJECT_PROPERTY_ACTION_TILL = 3,
	WORLD_OBJECT_PROPERTY_ACTION_WATERCROP = 4,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_TOMATO = 5,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_CUCUMBER = 6,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_CARROT = 7,
	WORLD_OBJECT_PROPERTY_ACTION_HARVEST_TOMATO = 8,
	WORLD_OBJECT_PROPERTY_ACTION_HARVEST_CUCUMBER = 9,
	WORLD_OBJECT_PROPERTY_ACTION_HARVEST_CARROT = 10,
	WORLD_OBJECT_PROPERTY_CAPACITY_10 = 11,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_0 = 12,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_1 = 13,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_2 = 14,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_3 = 15,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_4 = 16,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_5 = 17,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_6 = 18,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_7 = 19,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_8 = 20,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_9 = 21,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_10 = 22,
	WORLD_OBJECT_PROPERTY_DELETES_WHEN_FILLED_WITH_0 = 23
};

#endif
