#ifndef WORLD_OBJECT_PROPERTIES
#define WORLD_OBJECT_PROPERTIES

enum WorldObjectProperty
{
	WORLD_OBJECT_PROPERTY_PICKUPABLE = 0,
	WORLD_OBJECT_PROPERTY_ACTION_FILL_WATER_CONTAINER = 1,
	WORLD_OBJECT_PROPERTY_ACTION_SLEEP = 2,
	WORLD_OBJECT_PROPERTY_ACTION_TILL = 3,
	WORLD_OBJECT_PROPERTY_ACTION_WATERCROP = 4,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_TOMATO = 5,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_CUCUMBER = 6,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_CARROT = 7,
	WORLD_OBJECT_PROPERTY_CAPACITY_10 = 8,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_10 = 9,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_9 = 10,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_8 = 11,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_7 = 12,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_6 = 13,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_5 = 14,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_4 = 15,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_3 = 16,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_2 = 17,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_1 = 18,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_0 = 19
};

#endif
