#ifndef WORLD_OBJECT_PROPERTIES
#define WORLD_OBJECT_PROPERTIES

enum WorldObjectProperty
{
	WORLD_OBJECT_PROPERTY_PICKUPABLE = 0,
	WORLD_OBJECT_PROPERTY_ACTION_FILL_WATER_CONTAINER = 1,
	WORLD_OBJECT_PROPERTY_ACTION_SLEEP = 2,
	WORLD_OBJECT_PROPERTY_ACTION_TILL = 3,
	WORLD_OBJECT_PROPERTY_ACTION_WATERCROP = 4,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_TOMATO = 5,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_CUCUMBER = 6,
	WORLD_OBJECT_PROPERTY_ACTION_PLANT_SEEDS_CARROT = 7,
	WORLD_OBJECT_PROPERTY_ACTION_HARVEST_TOMATO = 8,
	WORLD_OBJECT_PROPERTY_ACTION_HARVEST_CUCUMBER = 9,
	WORLD_OBJECT_PROPERTY_ACTION_HARVEST_CARROT = 10,
	WORLD_OBJECT_PROPERTY_CAPACITY_10 = 11,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_ZERO = 12,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_ONE = 13,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_TWO = 14,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_THREE = 15,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_FOUR = 16,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_FIVE = 17,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_SIX = 18,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_SEVEN = 19,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_EIGHT = 20,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_NINE = 21,
	WORLD_OBJECT_PROPERTY_FILLED_WITH_TEN = 22,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_10 = 23,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_9 = 24,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_8 = 25,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_7 = 26,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_6 = 27,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_5 = 28,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_4 = 29,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_3 = 30,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_2 = 31,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_1 = 32,
	WORLD_OBJECT_PROPERTY_CURRENT_USES_LEFT_0 = 33
};

#endif
